//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.235
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DME.Dialer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DME.Dialer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} contained a non-interactive flag, however the authentication protocol  must display a UI to obtain the required identity information. 的本地化字符串。
        /// </summary>
        internal static string Argument_EapOptionsRequireInteractiveMode {
            get {
                return ResourceManager.GetString("Argument_EapOptionsRequireInteractiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phone number cannot be an empty string if the entry name has not been provided. 的本地化字符串。
        /// </summary>
        internal static string Argument_EmptyEntryNameAndPhoneNumber {
            get {
                return ResourceManager.GetString("Argument_EmptyEntryNameAndPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; already exists in the phone book. 的本地化字符串。
        /// </summary>
        internal static string Argument_EntryAlreadyExists {
            get {
                return ResourceManager.GetString("Argument_EntryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} contains an incorrect address family. 的本地化字符串。
        /// </summary>
        internal static string Argument_IncorrectAddressFamily {
            get {
                return ResourceManager.GetString("Argument_IncorrectAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} &apos;{1}&apos; is invalid. Ensure the entry does not already exist in the phone book, and does not contain invalid characters. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidEntryName {
            get {
                return ResourceManager.GetString("Argument_InvalidEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; contains an invalid file name. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidFileName {
            get {
                return ResourceManager.GetString("Argument_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; was not a valid handle. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidHandle {
            get {
                return ResourceManager.GetString("Argument_InvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; contains invalid or conflicting settings. Please verify the settings are correct and try again. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidOrConflictingEntrySettings {
            get {
                return ResourceManager.GetString("Argument_InvalidOrConflictingEntrySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; must have the PhoneNumber, DeviceType, DeviceName, FramingProtocol, and EntryType properties set as a minimum. 的本地化字符串。
        /// </summary>
        internal static string Argument_MissingRequiredInfo {
            get {
                return ResourceManager.GetString("Argument_MissingRequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; cannot be a null reference or empty string. 的本地化字符串。
        /// </summary>
        internal static string Argument_StringCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Argument_StringCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must be greater than zero. 的本地化字符串。
        /// </summary>
        internal static string Argument_ValueCannotBeLessThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Argument_ValueCannotBeLessThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cannot be less than zero. 的本地化字符串。
        /// </summary>
        internal static string Argument_ValueCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("Argument_ValueCannotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; specified is longer than the string. 的本地化字符串。
        /// </summary>
        internal static string Argument_ValueLongerThanString {
            get {
                return ResourceManager.GetString("Argument_ValueLongerThanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must be greater than zero and less than or equal to {1}. 的本地化字符串。
        /// </summary>
        internal static string Argument_ValueMustBeGreaterThanZeroLessThanOrEqualToOtherValue {
            get {
                return ResourceManager.GetString("Argument_ValueMustBeGreaterThanZeroLessThanOrEqualToOtherValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        internal static string CatAppearance {
            get {
                return ResourceManager.GetString("CatAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior 的本地化字符串。
        /// </summary>
        internal static string CatBehavior {
            get {
                return ResourceManager.GetString("CatBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string CatData {
            get {
                return ResourceManager.GetString("CatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string CatLayout {
            get {
                return ResourceManager.GetString("CatLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The caption of the dialog box. 的本地化字符串。
        /// </summary>
        internal static string CPDCaptionDesc {
            get {
                return ResourceManager.GetString("CPDCaptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the user name should be disabled. 的本地化字符串。
        /// </summary>
        internal static string CPDDisableUserNameDesc {
            get {
                return ResourceManager.GetString("CPDDisableUserNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum length of the password. 的本地化字符串。
        /// </summary>
        internal static string CPDMaxPasswordLengthDesc {
            get {
                return ResourceManager.GetString("CPDMaxPasswordLengthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum length of the user name. 的本地化字符串。
        /// </summary>
        internal static string CPDMaxUserNameLengthDesc {
            get {
                return ResourceManager.GetString("CPDMaxUserNameLengthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message of the dialog box. 的本地化字符串。
        /// </summary>
        internal static string CPDMessageDesc {
            get {
                return ResourceManager.GetString("CPDMessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the user should be notified the password was incorrect. 的本地化字符串。
        /// </summary>
        internal static string CPDNotifyIncorrectPasswordDesc {
            get {
                return ResourceManager.GetString("CPDNotifyIncorrectPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password. 的本地化字符串。
        /// </summary>
        internal static string CPDPasswordDesc {
            get {
                return ResourceManager.GetString("CPDPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the save check box will be checked. 的本地化字符串。
        /// </summary>
        internal static string CPDSaveCheckedDesc {
            get {
                return ResourceManager.GetString("CPDSaveCheckedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the &apos;Remember my password&apos; check box will be shown. 的本地化字符串。
        /// </summary>
        internal static string CPDShowSaveCheckBoxDesc {
            get {
                return ResourceManager.GetString("CPDShowSaveCheckBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target name. 的本地化字符串。
        /// </summary>
        internal static string CPDTargetNameDesc {
            get {
                return ResourceManager.GetString("CPDTargetNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user name. 的本地化字符串。
        /// </summary>
        internal static string CPDUserNameDesc {
            get {
                return ResourceManager.GetString("CPDUserNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the phone book entry to modify. 的本地化字符串。
        /// </summary>
        internal static string EPBEDEntryNameDesc {
            get {
                return ResourceManager.GetString("EPBEDEntryNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The caller does not have the required permission to perform the action requested. 的本地化字符串。
        /// </summary>
        internal static string Exception_AccessDeniedBySecurity {
            get {
                return ResourceManager.GetString("Exception_AccessDeniedBySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entry is not associated with a phone book. 的本地化字符串。
        /// </summary>
        internal static string Exception_EntryNotInPhoneBook {
            get {
                return ResourceManager.GetString("Exception_EntryNotInPhoneBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The handle is not network access protection (NAP) capable. 的本地化字符串。
        /// </summary>
        internal static string Exception_HandleNotNapCapable {
            get {
                return ResourceManager.GetString("Exception_HandleNotNapCapable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection must be a valid IKEv2 connection. 的本地化字符串。
        /// </summary>
        internal static string Exception_InvalidIkeV2Handle {
            get {
                return ResourceManager.GetString("Exception_InvalidIkeV2Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The handle is invalid or closed. 的本地化字符串。
        /// </summary>
        internal static string Exception_InvalidOrClosedHandle {
            get {
                return ResourceManager.GetString("Exception_InvalidOrClosedHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported on the current platform. 的本地化字符串。
        /// </summary>
        internal static string Exception_NotSupportedOnPlatform {
            get {
                return ResourceManager.GetString("Exception_NotSupportedOnPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation has timed out. 的本地化字符串。
        /// </summary>
        internal static string Exception_OperationTimedOut {
            get {
                return ResourceManager.GetString("Exception_OperationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phone book is corrupted or missing components. 的本地化字符串。
        /// </summary>
        internal static string Exception_PhonebookCorrupted {
            get {
                return ResourceManager.GetString("Exception_PhonebookCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phone book must be opened prior to performing this operation. 的本地化字符串。
        /// </summary>
        internal static string Exception_PhoneBookNotOpened {
            get {
                return ResourceManager.GetString("Exception_PhoneBookNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phone number or entry name (with phone book path) is required to dial an entry. 的本地化字符串。
        /// </summary>
        internal static string Exception_PhoneNumberOrEntryNameRequired {
            get {
                return ResourceManager.GetString("Exception_PhoneNumberOrEntryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application attempted to set default credentials for a per-user connection, or the user does not have the correct privileges to set pre-shared keys or credentials for all users. 的本地化字符串。
        /// </summary>
        internal static string Exception_SetCredentialsAccessDenied {
            get {
                return ResourceManager.GetString("Exception_SetCredentialsAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The TargetName property cannot be a null reference. 的本地化字符串。
        /// </summary>
        internal static string Exception_TargetNameCannotBeNullReference {
            get {
                return ResourceManager.GetString("Exception_TargetNameCannotBeNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The size of the object returned was not expected. 的本地化字符串。
        /// </summary>
        internal static string Exception_UnexpectedSizeReturned {
            get {
                return ResourceManager.GetString("Exception_UnexpectedSizeReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items within the collection cannot be set directly. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_ItemsCannotBeSet {
            get {
                return ResourceManager.GetString("NotSupported_ItemsCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of time (in seconds) before the connection attempt is aborted. 的本地化字符串。
        /// </summary>
        internal static string RADMConnectionQueryTimeoutDesc {
            get {
                return ResourceManager.GetString("RADMConnectionQueryTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether AutoDial displays a dialog box to query the user before creating a connection. 的本地化字符串。
        /// </summary>
        internal static string RADMDisableConnectionQueryDesc {
            get {
                return ResourceManager.GetString("RADMDisableConnectionQueryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of time (in seconds) between AutoDial connection attempts. 的本地化字符串。
        /// </summary>
        internal static string RADMFailedConnectionTimeoutDesc {
            get {
                return ResourceManager.GetString("RADMFailedConnectionTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the system disables all AutoDial connections for the current session. 的本地化字符串。
        /// </summary>
        internal static string RADMLogOnSessionDisableDesc {
            get {
                return ResourceManager.GetString("RADMLogOnSessionDisableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of addresses that AutoDial stores in the registry. 的本地化字符串。
        /// </summary>
        internal static string RADMSavedAddressesLimitDesc {
            get {
                return ResourceManager.GetString("RADMSavedAddressesLimitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the dialog has encountered an error. 的本地化字符串。
        /// </summary>
        internal static string RCDErrorDesc {
            get {
                return ResourceManager.GetString("RCDErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The coordinates of the upper-left corner of the dialog box. 的本地化字符串。
        /// </summary>
        internal static string RCDLocationDesc {
            get {
                return ResourceManager.GetString("RCDLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the component has encountered an error. 的本地化字符串。
        /// </summary>
        internal static string RCErrorDesc {
            get {
                return ResourceManager.GetString("RCErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object used to marshal event-handler calls. 的本地化字符串。
        /// </summary>
        internal static string RCSyncObjectDesc {
            get {
                return ResourceManager.GetString("RCSyncObjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when a remote access connection sub-entry has connected. 的本地化字符串。
        /// </summary>
        internal static string RCWBandwidthAddedDesc {
            get {
                return ResourceManager.GetString("RCWBandwidthAddedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when a remote access connection sub-entry has disconnected. 的本地化字符串。
        /// </summary>
        internal static string RCWBandwidthRemovedDesc {
            get {
                return ResourceManager.GetString("RCWBandwidthRemovedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when a remote access connection is established. 的本地化字符串。
        /// </summary>
        internal static string RCWConnectedDesc {
            get {
                return ResourceManager.GetString("RCWConnectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when a remote access connection is disconnected. 的本地化字符串。
        /// </summary>
        internal static string RCWDisconnectedDesc {
            get {
                return ResourceManager.GetString("RCWDisconnectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the component will be enabled. 的本地化字符串。
        /// </summary>
        internal static string RCWEnableRaisingEventsDesc {
            get {
                return ResourceManager.GetString("RCWEnableRaisingEventsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether stored credentials will be allowed if the credentials have not been provided. 的本地化字符串。
        /// </summary>
        internal static string RDAllowUseStoredCredentialsDesc {
            get {
                return ResourceManager.GetString("RDAllowUseStoredCredentialsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the saved credentials will update upon completion of a successful connection attempt. 的本地化字符串。
        /// </summary>
        internal static string RDAutoUpdateCredentialsDesc {
            get {
                return ResourceManager.GetString("RDAutoUpdateCredentialsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The callback number for the remote server to dial. 的本地化字符串。
        /// </summary>
        internal static string RDCallbackNumberDesc {
            get {
                return ResourceManager.GetString("RDCallbackNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the asynchronous dial operation has completed. 的本地化字符串。
        /// </summary>
        internal static string RDDialCompletedDesc {
            get {
                return ResourceManager.GetString("RDDialCompletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phone number to dial (overriding the entry phone number). 的本地化字符串。
        /// </summary>
        internal static string RDDPhoneNumberDesc {
            get {
                return ResourceManager.GetString("RDDPhoneNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The extensible authentication protocol (EAP) options. 的本地化字符串。
        /// </summary>
        internal static string RDEapOptionsDesc {
            get {
                return ResourceManager.GetString("RDEapOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entry options. 的本地化字符串。
        /// </summary>
        internal static string RDEntryOptionsDesc {
            get {
                return ResourceManager.GetString("RDEntryOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the polling interval, in milliseconds, to determine whether the connection has completed disconnecting. 的本地化字符串。
        /// </summary>
        internal static string RDHangUpPollingIntervalDesc {
            get {
                return ResourceManager.GetString("RDHangUpPollingIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The interface index on which the VPN connection will be dialed. 的本地化字符串。
        /// </summary>
        internal static string RDInterfaceIndexDesc {
            get {
                return ResourceManager.GetString("RDInterfaceIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether to not call the custom dial entry point of the custom dialer. 的本地化字符串。
        /// </summary>
        internal static string RDOCustomDialDesc {
            get {
                return ResourceManager.GetString("RDOCustomDialDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether to disable the connected user interface. 的本地化字符串。
        /// </summary>
        internal static string RDODisableConnectedUIDesc {
            get {
                return ResourceManager.GetString("RDODisableConnectedUIDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether to disable reconnect. 的本地化字符串。
        /// </summary>
        internal static string RDODisableReconnectDesc {
            get {
                return ResourceManager.GetString("RDODisableReconnectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether to disable the reconnect user interface. 的本地化字符串。
        /// </summary>
        internal static string RDODisableReconnectUIDesc {
            get {
                return ResourceManager.GetString("RDODisableReconnectUIDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether no user is present. 的本地化字符串。
        /// </summary>
        internal static string RDONoUserDesc {
            get {
                return ResourceManager.GetString("RDONoUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether to accept paused states. 的本地化字符串。
        /// </summary>
        internal static string RDOPausedStatesDesc {
            get {
                return ResourceManager.GetString("RDOPausedStatesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the connecting device is a router. 的本地化字符串。
        /// </summary>
        internal static string RDORouterDesc {
            get {
                return ResourceManager.GetString("RDORouterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether to set the modem speaker. 的本地化字符串。
        /// </summary>
        internal static string RDOSetModemSpeakerDesc {
            get {
                return ResourceManager.GetString("RDOSetModemSpeakerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether to enable software compression. 的本地化字符串。
        /// </summary>
        internal static string RDOSetSoftwareCompressionDesc {
            get {
                return ResourceManager.GetString("RDOSetSoftwareCompressionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the dialer should invoke a custom-scripting DLL after connecting. 的本地化字符串。
        /// </summary>
        internal static string RDOUseCustomScriptingDesc {
            get {
                return ResourceManager.GetString("RDOUseCustomScriptingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the prefix and suffix that is in the phone book should be used. 的本地化字符串。
        /// </summary>
        internal static string RDOUsePrefixSuffixDesc {
            get {
                return ResourceManager.GetString("RDOUsePrefixSuffixDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parent window used for dialog box creation and centering. 的本地化字符串。
        /// </summary>
        internal static string RDOwnerDesc {
            get {
                return ResourceManager.GetString("RDOwnerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The full path (including file name) of the phone book. 的本地化字符串。
        /// </summary>
        internal static string RDPhoneBookPathDesc {
            get {
                return ResourceManager.GetString("RDPhoneBookPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether point-to-point authentication is skipped. 的本地化字符串。
        /// </summary>
        internal static string RDSkipPppAuthDesc {
            get {
                return ResourceManager.GetString("RDSkipPppAuthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the connection state changes. 的本地化字符串。
        /// </summary>
        internal static string RDStateChangedDesc {
            get {
                return ResourceManager.GetString("RDStateChangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The zero-based index of the sub-entry to dial. 的本地化字符串。
        /// </summary>
        internal static string RDSubEntryIdDesc {
            get {
                return ResourceManager.GetString("RDSubEntryIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of time (in milliseconds) until the asynchronous connection attempt times out. 的本地化字符串。
        /// </summary>
        internal static string RDTimeoutDesc {
            get {
                return ResourceManager.GetString("RDTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the user data is obtained from WinLogon. 的本地化字符串。
        /// </summary>
        internal static string REAPOLogOnDesc {
            get {
                return ResourceManager.GetString("REAPOLogOnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the authentication protocol should not display a graphical user interface. 的本地化字符串。
        /// </summary>
        internal static string REAPONonInteractiveDesc {
            get {
                return ResourceManager.GetString("REAPONonInteractiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the user should be prompted for identity information before dialing. 的本地化字符串。
        /// </summary>
        internal static string REAPOPreviewDesc {
            get {
                return ResourceManager.GetString("REAPOPreviewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the entry. 的本地化字符串。
        /// </summary>
        internal static string REDEntryNameDesc {
            get {
                return ResourceManager.GetString("REDEntryNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether entries cannot be renamed while in edit mode. 的本地化字符串。
        /// </summary>
        internal static string REDNoRenameDesc {
            get {
                return ResourceManager.GetString("REDNoRenameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The full path (including file name) of the phone book to modify. 的本地化字符串。
        /// </summary>
        internal static string REDPhoneBookPathDesc {
            get {
                return ResourceManager.GetString("REDPhoneBookPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phone number to dial. 的本地化字符串。
        /// </summary>
        internal static string REDPhoneNumberDesc {
            get {
                return ResourceManager.GetString("REDPhoneNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The style of dialog box to display. 的本地化字符串。
        /// </summary>
        internal static string REDRasDialogStyleDesc {
            get {
                return ResourceManager.GetString("REDRasDialogStyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the phone book has changed. 的本地化字符串。
        /// </summary>
        internal static string RPBChangedDesc {
            get {
                return ResourceManager.GetString("RPBChangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the user creates a new entry or copies an existing entry. 的本地化字符串。
        /// </summary>
        internal static string RPBDAddedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDAddedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the user changes an existing phone book entry. 的本地化字符串。
        /// </summary>
        internal static string RPBDChangedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDChangedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the user successfully dials an entry. 的本地化字符串。
        /// </summary>
        internal static string RPBDDialedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDDialedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the phone book has been deleted. 的本地化字符串。
        /// </summary>
        internal static string RPBDeletedDesc {
            get {
                return ResourceManager.GetString("RPBDeletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the entry to initially highlight. 的本地化字符串。
        /// </summary>
        internal static string RPBDEntryNameDesc {
            get {
                return ResourceManager.GetString("RPBDEntryNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the user removes a phone book entry. 的本地化字符串。
        /// </summary>
        internal static string RPBDRemovedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDRemovedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the phone book file will be monitored for external changes. 的本地化字符串。
        /// </summary>
        internal static string RPBEnableFileWatcherDesc {
            get {
                return ResourceManager.GetString("RPBEnableFileWatcherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the phone book has been renamed. 的本地化字符串。
        /// </summary>
        internal static string RPBRenamedDesc {
            get {
                return ResourceManager.GetString("RPBRenamedDesc", resourceCulture);
            }
        }
    }
}
